### ISSUE TITLE
Support Elysia 1.0.0

### ISSUE THREAD

**Issue by david-plugge** [bogeychan/elysia-logger#14] opened 2024-03-17 09:15 UTC
### What versions are running?

I'm using Elysia version `1.0.0` and the latest version of this package (`^0.0.17`)

### What steps can reproduce the bug?

```ts
const app = new Elysia({})
	.use(logger({ autoLogging: true })) // -> results in a type error and logs nothing
        .listen(3000)
```

**Comment by bogeychan** [comment] 2024-03-17 23:19
Hi 👋

this should be fixed with `0.0.18`. Let me know if the issue persists.

**Comment by MAST1999** [comment] 2024-03-18 12:22
Hey

I still have some problems with the latest version of both Elysia and logger:

```json
  "dependencies": {
    "@bogeychan/elysia-logger": "^0.0.18",
    "@bogeychan/elysia-polyfills": "latest",
    "@elysiajs/cors": "^1.0.2",
    "@elysiajs/swagger": "^1.0.2",
    "drizzle-typebox": "^0.1.1",
    "elysia": "^1.0.3",
    "uuid": "^9.0.1"
  }
```

![image](https://github.com/bogeychan/elysia-logger/assets/48868969/660bcc9a-af85-4c05-8bc2-4f4831e4a96d)

**Comment by raggesilver** [comment] 2024-03-19 11:42
Version 0.0.18 fixes the TypeScript errors for me, but it doesn't work. Nothing gets logged, neither automatically (on request) nor manually (`({ log }) => log.info("Doesn't work")`).

**Comment by bogeychan** [comment] 2024-03-19 17:55
@MAST1999, @raggesilver can you share a bigger code snipped please. i can't reproduce it on my end.

this works for me:

```ts
import { Elysia } from "elysia";
import { logger } from "@bogeychan/elysia-logger";

export const app = new Elysia()
  .use(logger())
  .get("/", ({ log }) => {
    log.info("yay");
    return "";
  })
  .listen(8080);

console.log(`${app.server?.url}`);
```

```json
{
  "dependencies": {
    "@bogeychan/elysia-logger": "0.0.18",
    "elysia": "1.0.0"
  }
}
```

```bash
bun --version # 1.0.32
```

**Comment by MAST1999** [comment] 2024-03-19 18:09
> @MAST1999, @raggesilver can you share a bigger code snipped please. i can't reproduce it on my end.
> 
> this works for me:
> 
> ```ts
> import { Elysia } from "elysia";
> import { logger } from "@bogeychan/elysia-logger";
> 
> export const app = new Elysia()
>   .use(logger())
>   .get("/", ({ log }) => {
>     log.info("yay");
>     return "";
>   })
>   .listen(8080);
> 
> console.log(`${app.server?.url}`);
> ```
> 
> ```json
> {
>   "dependencies": {
>     "@bogeychan/elysia-logger": "0.0.18",
>     "elysia": "1.0.0"
>   }
> }
> ```
> 
> ```bash
> bun --version # 1.0.33
> ```

I'll try to set up a repo later.

I'll just add I'm using the node compat and pnpm so that might effect things.

**Comment by raggesilver** [comment] 2024-03-19 23:32
> @MAST1999, @raggesilver can you share a bigger code snipped please. i can't reproduce it on my end.
> 
> this works for me:
> 
> ```ts
> import { Elysia } from "elysia";
> import { logger } from "@bogeychan/elysia-logger";
> 
> export const app = new Elysia()
>   .use(logger())
>   .get("/", ({ log }) => {
>     log.info("yay");
>     return "";
>   })
>   .listen(8080);
> 
> console.log(`${app.server?.url}`);
> ```
> 
> ```json
> {
>   "dependencies": {
>     "@bogeychan/elysia-logger": "0.0.18",
>     "elysia": "1.0.0"
>   }
> }
> ```
> 
> ```shell
> bun --version # 1.0.33
> ```

This doesn't work for me:

```ts
import { Elysia } from "elysia";
import { logger } from "@bogeychan/elysia-logger";

export const app = new Elysia()
  .use(logger({ autoLogging: true })) // Enable auto-logging
  .get("/", ({ log }) => {
    // log.info("yay"); // Comment this out
    return "";
  })
  .listen(8080);

console.log(`${app.server?.url}`);
```

HTTP requests are not logged. Using pinto-pretty as transport doesn't fix it.

**Comment by dgpt** [comment] 2024-03-20 07:03
^ +1 I'm seeing the same thing using elysia 1.0.4 and `"@bogeychan/elysia-logger": "^0.0.18",`. Set up exactly as instructed in the readme and I'm seeing no logs. Also tried using pino-pretty as transport to no avail.

**Comment by bogeychan** [comment] 2024-03-20 15:05
@raggesilver, thanks for the code. `autoLogging` works now by default (as described in the readme). please update to `0.0.19`.

**Comment by raggesilver** [comment] 2024-03-20 16:18
@bogeychan, auto logging works in `0.0.19`. Thanks!

**Comment by jonasfroeller** [comment] 2024-03-22 22:47
I get this type error using the latest versions of elysia and the logger:

```ts
Type 'Elysia<"", false, { decorator: {}; store: { readonly startTime?: number | undefined; readonly endTime?: number | undefined; readonly responseTime?: number | undefined; }; derive: { readonly log: Logger; }; resolve: {}; }, ... 4 more ..., { ...; }>' is not assignable to type 'Elysia<"", false, { decorator: {}; store: {}; derive: {}; resolve: {}; }, { type: {}; error: {}; }, { schema: {}; macro: {}; }, {}, { derive: {}; resolve: {}; schema: {}; }, { derive: {}; resolve: {}; schema: {}; }>'.
  Types of property 'onStart' are incompatible.
    Type '(handler: MaybeArray<GracefulHandler<Elysia<"", false, { decorator: {}; store: { readonly startTime?: number | undefined; readonly endTime?: number | undefined; readonly responseTime?: number | undefined; }; derive: { ...; }; resolve: {}; }, ... 4 more ..., { ...; }>>>) => Elysia<...>' is not assignable to type '(handler: MaybeArray<GracefulHandler<Elysia<"", false, { decorator: {}; store: {}; derive: {}; resolve: {}; }, { type: {}; error: {}; }, { schema: {}; macro: {}; }, {}, { derive: {}; resolve: {}; schema: {}; }, { derive: {}; resolve: {}; schema: {}; }>>>) => Elysia<...>'.
      Types of parameters 'handler' and 'handler' are incompatible.
        Type 'MaybeArray<GracefulHandler<Elysia<"", false, { decorator: {}; store: {}; derive: {}; resolve: {}; }, { type: {}; error: {}; }, { schema: {}; macro: {}; }, {}, { derive: {}; resolve: {}; schema: {}; }, { derive: {}; resolve: {}; schema: {}; }>>>' is not assignable to type 'MaybeArray<GracefulHandler<Elysia<"", false, { decorator: {}; store: { readonly startTime?: number | undefined; readonly endTime?: number | undefined; readonly responseTime?: number | undefined; }; derive: { readonly log: Logger; }; resolve: {}; }, ... 4 more ..., { ...; }>>>'.
          Type 'GracefulHandler<Elysia<"", false, { decorator: {}; store: {}; derive: {}; resolve: {}; }, { type: {}; error: {}; }, { schema: {}; macro: {}; }, {}, { derive: {}; resolve: {}; schema: {}; }, { derive: {}; resolve: {}; schema: {}; }>>' is not assignable to type 'MaybeArray<GracefulHandler<Elysia<"", false, { decorator: {}; store: { readonly startTime?: number | undefined; readonly endTime?: number | undefined; readonly responseTime?: number | undefined; }; derive: { readonly log: Logger; }; resolve: {}; }, ... 4 more ..., { ...; }>>>'.ts(2322)
```

versions I used (latest):
```json
"@bogeychan/elysia-logger": "^0.0.19",
"elysia": "^1.0.7"
```

**Comment by bogeychan** [comment] 2024-03-26 20:13
@jonasfroeller thanks for reporting. this should be fixed with `0.0.20` release.

@MariNatsuki, thanks for your contribution 🚀

**Comment by abhi-slash-git** [comment] 2024-03-26 21:30
```
Exported variable 'v1Routes' has or is using name 'BaseLoggerOptions' from external module "node_modules/@bogeychan/elysia-logger/dist/types" but cannot be named. ts(4023)
```

Getting this type error when using this plugin

**Comment by bogeychan** [comment] 2024-03-26 22:07
@abhi-slash-git, can you share a code snipped, your `tsconfig` & build script please. i can't reproduce it on my end

**Comment by MAST1999** [comment] 2024-04-08 13:07
Just wanted to report that it works for me now!

Thanks a lot!

**Closed** 2024-04-08 14:13 UTC
Labels: bug
